# Generated by Django 2.0.9 on 2019-01-15 15:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Company country', max_length=2, null=True)),
                ('region', models.CharField(blank=True, help_text='Region', max_length=60, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=60, null=True)),
                ('address', models.CharField(blank=True, help_text='Address', max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['id'],
            },
        ),
    ]
