version: '3'

services:
  djangoapp:
    container_name: foobar_djangoapp
    build:
      context: .
    networks:
      - django_nginx
      - foobar_network
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - postgres

  nginx:
    container_name: foobar_nginx
    image: nginx:1.15-alpine
    networks:
      - django_nginx
    volumes:
      - ./config/nginx/dev:/etc/nginx/conf.d
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/static
    ports:
      - 443:443
      - 8000:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - djangoapp

  postgres:  # <-- IMPORTANT: same name as in DATABASES setting
    container_name: foobar_postgres
    image: postgres:10-alpine
    ports:
      - 5432:5432
    env_file:
      - config/postgres/foobar.env
    networks:
      - foobar_network
    volumes:
      - foobar_volume:/var/lib/postgresql/data

volumes:
  foobar_volume:
  static_volume:
  media_volume:

networks:
  django_nginx:
    driver: bridge
  foobar_network:
    driver: bridge
