version: '3'

services:
  djangoapp:
    container_name: foobar_djangoapp
    build:
      context: .
    networks:
      - django_nginx
      - foobar_network
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - postgres
    deploy:
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 3

  nginx:
    container_name: foobar_nginx
    image: nginx:1.15
    networks:
      - django_nginx
    volumes:
      - ./config/nginx/prod:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/static
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - djangoapp
    deploy:
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 3

  postgres:  # <-- IMPORTANT: same name as in DATABASES setting
    container_name: foobar_postgres
    image: postgres:10
    ports:
      - 5432:5432
    env_file:
      - config/postgres/foobar.env
    networks:
      - foobar_network
    volumes:
      - foobar_volume:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3

  certbot:
    container_name: foobar_certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 3

volumes:
  foobar_volume:
  static_volume:
  media_volume:

networks:
  django_nginx:
    driver: bridge
  foobar_network:
    driver: bridge
