version: '3'
services:

  django:
    container_name: dsne-django
    build:
      context: .
    networks:
      - dsne-django-nginx
    volumes:
      - dsne-django-static:/usr/src/app/static

  nginx:
    container_name: dsne-nginx
    image: nginx:1.15-alpine
    # build:
    #   context: ./nginx
    #   dockerfile: nginx.dockerfile
    networks:
      - dsne-django-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # .........
      - dsne-django-static:/usr/src/app/static
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
      # - 8000:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  dsne-django-static:

networks:
  dsne-django-nginx:
    driver: bridge
