# Generated by Django 2.0.9 on 2019-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Last Name')),
            ],
        ),
    ]
